import {useEffect} from 'react';
import Head from 'next/head'

function HeadMeta({children,title}) {
  let uA,isRobot;
  useEffect(() => {
    let uA = window.navigator.userAgent;
    let isRobot = /bot|spider|crawl/i.test(uA);
  }, [])
  
  return (
    <Head>
        <title>{title || "nextjs"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        {
          isRobot ||
          (
            <>
              <meta property="og:title" content={title || "nextjs"} />
              <meta property="og:type" content="website" />
              <meta property="og:article:author" content="nextjs" />
            </>
          )
        }
        {children}
    </Head>
  )
}

export default HeadMeta