import Head from 'next/head'

export default function HeadMeta({children,title,isRobot}) {
  return (
    <Head>
        <title>{title || "nextjs"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        {
          !isRobot ||
          (
            <>
              <meta property="og:title" content={title || "nextjs"} />
              <meta property="og:type" content="website" />
              <meta property="og:article:author" content="nextjs" />
            </>
          )
        }
        {children}
    </Head>
  )
}

